### ISSUE TITLE
Unable to install resin-cli on macOS

### ISSUE THREAD

**Issue by zrzka** [resin-io/resin-cli#898] opened 2018-06-20 12:10 UTC
# Environment

* node 10.4.1
* npm 6.1.0
* macOS High Sierra 10.13.5 (17F77)

# Installation

Installation command `npm install resin-cli -g --production`. Full logs attached. Seems like an issue in the `ext2fs@1.0.7` package:

```
20431 verbose stack Error: ext2fs@1.0.7 install: `prebuild-install || node-gyp rebuild`
20431 verbose stack Exit status 1
20431 verbose stack     at EventEmitter.<anonymous> (/Users/robertvojta/.nvm/versions/node/v10.4.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
20431 verbose stack     at EventEmitter.emit (events.js:182:13)
20431 verbose stack     at ChildProcess.<anonymous> (/Users/robertvojta/.nvm/versions/node/v10.4.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
20431 verbose stack     at ChildProcess.emit (events.js:182:13)
20431 verbose stack     at maybeClose (internal/child_process.js:961:16)
20431 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
20432 verbose pkgid ext2fs@1.0.7
```

# Logs

[2018-06-20T12_03_58_783Z-debug.txt](https://github.com/resin-io/resin-cli/files/2119171/2018-06-20T12_03_58_783Z-debug.txt)

# Workaround

Download [v7.5.2](https://github.com/resin-io/resin-cli/releases/tag/v7.5.2), unzip, update `PATH` and it works.

**Comment by pimterry** [comment] 2018-06-25 16:13
Glad you've found the standalone install works well as a workaround for this. In future, we're planning on making that the primary install mechanism (with a full installer, not just a zip file), so issues like this should disappear.

It'd be interesting to check what the problem is here anyway though. I notice you're not passing an `--unsafe-perm` argument to `npm install`. That's required because with some configurations native builds may not be able to write to the global directory. If you add that argument, does the install work successfully?

**Comment by zrzka** [comment] 2018-06-26 05:52
Hi @pimterry, sorry that I forgot to mention it. I tried `--unsafe-param` as well. Basically same error.

```
  CC(target) Release/obj.target/ext2fs/deps/e2fsprogs/lib/ext2fs/version.o
  CC(target) Release/obj.target/ext2fs/deps/e2fsprogs/lib/ext2fs/write_bb_file.o
  LIBTOOL-STATIC Release/libext2fs.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/libext2fs.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/robertvojta/.nvm/versions/node/v10.4.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/Users/robertvojta/.nvm/versions/node/v10.4.1/bin/node" "/Users/robertvojta/.nvm/versions/node/v10.4.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/robertvojta/.nvm/versions/node/v10.4.1/lib/node_modules/resin-cli/node_modules/ext2fs
gyp ERR! node -v v10.4.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: removedrive@1.1.2 (node_modules/resin-cli/node_modules/removedrive):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for removedrive@1.1.2: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ext2fs@1.0.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ext2fs@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Was googling little bit ...

```
  LIBTOOL-STATIC Release/libext2fs.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
```

... and lot of similar issues - the problem is that `node-gyp` doesn't support Python 3.x.

```
 2018-06-26 07:47:07 ⌚  Zrzka in ~
○ → python --version
Python 3.6.1 :: Anaconda custom (64-bit)
```

It works when I change path to use system Python (**2.7**). Checked [README](https://github.com/resin-io/resin-cli#npm-install) again and it's there:

> In some environments, this process will need to build native modules. This may require a more complex build environment, and notably requires Python 2.7. If you hit any problems with this, we recommend you try the alternative standalone install below instead.

I'd recommend to:

* add check for Python 2.7 before build starts,
* emphasis this information in the README and add it **before** `npm install ...`.

I don't know anyone who does use Python 2.7 (system one) on macOS and these slight changes can help you to minimize number of issues like this one.

Anyway, it's totally my fault and sorry for the buzz. Feel free to close this issue if you do not want to make proposed changes.

**Comment by pimterry** [comment] 2018-06-26 16:34
Thanks for looking into this further.

The Python point is an issue, but it's not one most users should ever hit. The real root issue here was a partially failed deploy of ext2fs: https://github.com/resin-io/node-ext2fs/issues/30. We provide prebuilt binaries for our native modules, so almost all environments you shouldn't ever do a native build at all, and your Python version wouldn't matter.

In this case though the prebuilt binary deploy seems to have failed to publish correctly for Node 10 on Linux & OSX, so with no prebuilt binary it fell back to a native build on your machine, causing your problem.

This is fixed now - if you do a fresh install with any Python version it should work fine. Let us know if it doesn't, and thanks for all your work investigating this!

**Closed by pimterry** 2018-06-26 16:34 UTC

**Comment by zrzka** [comment] 2018-06-26 17:31
Okay, tested it again with ...

```
○ → python --version
Python 3.6.4 :: Anaconda, Inc.
```

... and node 8.11.3 (LTS) & 10.5.0 (latest). Works like a charm. Thanks for fixing this!

**Comment by cara** [comment] 2018-11-25 13:09
npm config set python python2.7
