### ISSUE TITLE
"resin env rm <id>" is successful, but does not delete the env var

### ISSUE THREAD

**Issue by pguelpa** [resin-io/resin-cli#726] opened 2017-11-30 02:11 UTC
- **resin-cli version:** 6.10.2 (also verified on 6.6.13)
- **Operating system and architecture:** OS X 10.12.6

I'm working on scripting my device setup and I'm having trouble with the `resin env rm <id>` command.

I'm running: `resin env rm <id> --device <uuid>` and it asks if I'd like to delete the environment variable and exits successfully (exit code 0) with no other output, but the environment variable is not deleted.

One other minor thing I noticed is that it looks like the SDK accepts a numeric id or a string for the `<id>`, but when I use a string I get an error `ResinRequestError: Request error: invalid input syntax for integer: "SSL_CERTIFICATE"`. It would be great if I could use the string from the CLI as the internal id is a bit more work to parse out.

**Comment by pimterry** [comment] 2017-12-11 13:15
Hi @pguelpa this is very odd. I can reproduce it locally though, so you're totally right, and it definitely looks like a bug. I'll get it fixed up now.

**Comment by pimterry** [comment] 2017-12-11 13:36
Ah, got it. This is not a bug in the deletion as such, it's very odd UX that comes from some odd behaviour in our CLI parsing somewhere... The issue is that your command line arguments here aren't quite right, so are being misinterpreted. The right command is:

```
resin env rm <id> --device
```

The `--device` is a boolean flag, not a way to pass a specific device uuid. Providing the extra UUID confuses something, and the code treats it as if you didn't pass `--device` at all, so tries to delete an _app_ env var with that id. That doesn't exist, but trying to delete something when it already doesn't exist is considered successful (also dubious behaviour).

Let me know if the command above still doesn't work for you, but it seems to now behave correctly for me.

Otherwise, I'm not planning to change anything else here immediately, but we do have some upcoming work for multicontainer which is going to change this API substantially, probably into something more like:

```
resin env rm --app <id> <env var key>
resin env rm --device <uuid> <env var key>
```

which should solve this problem, and also fix your second point about needing device env var ids entirely, and use the uniqueness of env var key + device/app directly instead. Would that work for you?

**Comment by pimterry** [comment] 2017-12-18 10:21
I'm going to close this for now. We will be looking into improving the overall UX of this command in future, as part of other incoming updates, and hopefully the above corrected command line format works for you for now.

Do feel free to ping here if you're still facing this issue though, and we can take a closer look.

**Closed by pimterry** 2017-12-18 10:21 UTC
Labels: priority:high, type:bug
