### ISSUE TITLE
Wifi configuration incompatible with latest NetworkManager

### ISSUE THREAD

**Issue by willnewton** [resin-io/resin-cli#657] opened 2017-09-11 08:38 UTC
It appears that something has changed that is causing NetworkManager to reject config files generated by ```resin local configure```.

The error from the service is:

    keyfile: error loading connection from file /etc/NetworkManager/system-connections/resin-sample: invalid connection: 802-11-wireless-security.key-mgmt: property is missing

Adding the key-mgmt property to the security part of the config file fixes this:

    [wifi-security]
    key-mgmt=wpa-psk

As far as I know this property has been required by NetworkManager for a long time (2007?) so I'm not sure why this has suddenly started to be a problem.

**Comment by pimterry** [comment] 2017-11-29 10:45
@willnewton sorry this has been sat for a while, just looking at it now. I can't reproduce though - I've configured lots of images recently that all worked happily, and the built-in sample config from the CLI already has this property set: https://github.com/resin-io/resin-cli/blob/master/lib/actions/local/configure.coffee#L124.

The only way I can see this not being there is if you download an image from elsewhere with an existing `resin-sample` or `resin-wifi` file with this property missing, but that arguably isn't really a CLI issue. Do you have any images around where this happens, or any idea how you might get one?

**Comment by pimterry** [comment] 2017-12-12 11:09
Totally didn't connect the name, I'd forgotten you've left!

I can't reproduce this. There's been lots of changes here, but I'm pretty confident that it's not a problem on any obvious images right now, so we don't need to worry about it too much. If anybody does have an image where they can reproduce this I'd love to hear about it, but until then I'm closing this.

**Closed by pimterry** 2017-12-12 11:09 UTC
Labels: type:bug
