### ISSUE TITLE
resin device rm <uuid> returns an error if UUID is purely composed of numbers

### ISSUE THREAD

**Issue by lifeeth** [resin-io/resin-cli#489] opened 2017-04-19 17:36 UTC
when the short uuid is purely composed of numbers (Example: 585644) - resin device rm fails with the following error message.
`ResinDeviceNotFound: Device not found: 585644`

**Comment by emirotin** [comment] 2017-04-19 18:24
One more side effect of numbers autoparsing :( I find this feature more harmful than useful.

**Comment by lurch** [comment] 2017-06-01 12:01
Apologies if this is a naive question, but could the function that generates (short) UUIDs be modified to always include at least one letter?

**Comment by pimterry** [comment] 2017-06-01 12:06
We could do something like that, but it wouldn't help existing devices, and it shouldn't be necessary - the cli should know the type of any given parameter, so we just need to stop the parsing code from being too clever for it's own good.

**Comment by floion** [comment] 2017-07-10 08:16
I stumbled upon this problem now and as expected it is misbehaving also when doing resin ssh, resin sync etc

**Comment by michal-mazurek** [comment] 2017-08-02 12:57
I ran into this now. Prefixing the short UUID with "0x" doesn't fix this.

**Comment by lekkas** [comment] 2017-12-14 11:35
One more case where we hit this was when we wanted to search devices on the local network with `resin local scan` , get the `<short uuid>.local` hostnames and then perform a `resin device <short uuid>`. This was used while troubleshooting the Beast, to identify devices that had booted resinOS successfully (and would therefore broadcast avahi info) but hadn't been able to register themselves (e.g. faulty LAN cable)

For devices where the short uuid was numeric only, the error message can be confusing, because it implies that the device does not exist (`ResinDeviceNotFound: Device not found:`). The workaround was to use` resin-sdk` directly.

@pimterry is this related to Capitano? Do we need to make any product call decisions to change the number parsing behaviour?

**Comment by thgreasi** [comment] 2017-12-15 07:46
Since we will be deprecating device ID operations from our APIs, I think that we could have a fix for this, even as a patch release, with an approach like this:
* When the parameter is a number, check whether it's string representation is 7+ chars long
* In that case, pass the string casted parameter to the sdk
* In case that such a device is not found, then also try to fetch the device by passing the number to the sdk

Theoretically this isn't 100% bulletproof.
There can be an edge case that we can't reason, when a user uses a number for a custom device UUID that happens to be the same as the ID of an other device that they own.
On the other hand, this approach should provide a better experience overall, when weighting how often this occurs and how many people actually use custom device UUIDs of strange format. In any case, this should reduce the amount of affected people and we will be actually following the CLI DOCs that only mention the use of UUIDs for the `resin device` commands.

On the other hand, someone could reason that we don't actually need all that added complexity and we should **just cast all device parameters to string** before passing to the SDK. Again, that's what in the CLI DOCs.

@pimterry ?

**Comment by lurch** [comment] 2017-12-15 11:50
Just out of curiosity, would/could a similar issue affect the python-sdk @nghiant2710 ? Or is this definitely just isolated to the CLI?

**Comment by pimterry** [comment] 2017-12-15 18:16
@lurch The issue is in Capitano, so if there are any similar bugs in the Python-SDK, they're totally independent. Similar issues might very possibly affect the Etcher CLI though, since I think that's also built on Capitano?

@thgreasi Trying to do detection like that works logically, but is hard to implement in practice here, because argument interpretation lives entirely within Capitano, which is a generic CLI library and doesn't (and shouldn't) know about UUIDs.

We could add logic to every single function to work around that, or monkey patch Capitano somehow, but I'd sort of rather not...

The current plan was to build Capitano v2, which will let you explicitly specify the type of argument you're expecting (a string), which will fix this bug, and then allow us to _only_ take UUIDs in the CLI, because they'll work everywhere reliably and everybody will be happy forever.

That's not quick or easy though, so it wouldn't be solved soon. Normally you can work around it with a long UUID or an actual id, but I can see how that's awkward in cases like the one @lekkas describes... Are there any clean & easy short-term improvements we could make to avoid this?

**Comment by lurch** [comment] 2017-12-15 18:25
> The issue is in Capitano, so if there are any similar bugs in the Python-SDK, they're totally independent.

Good to hear :+1: 

> Similar issues might very possibly affect the Etcher CLI though, since I think that's also built on Capitano?

The only parameters that the Etcher CLI takes are image-path and drive-device, neither of which I think could me mis-interpreted as integers :)

I've never looked at the Capitano code, but from the position of an "outside observer" it seems kinda surprising that a CLI-argument-parsing library would attempt to 'detect' and auto-convert the types of any parameters, rather than simply passing through every parameter as a string and letting the client code do any conversions as and when necessary \*shrug\*

**Comment by lekkas** [comment] 2018-01-30 18:11
@pimterry what is the problem with following an approach similar to what @thgreasi is suggesting above:

> On the other hand, someone could reason that we don't actually need all that added complexity and we should just cast all device parameters to string before passing to the SDK. Again, that's what in the CLI DOCs.

Just to make it a bit more targeted, instead of *all* device parameters, we can cast `params.uuid` to string for every `resin device` command before passing its value to the SDK. Note that we will not be breaking any user-side expectations of the `resin device` command, since the docs clearly state that a uuid is expected.

**Comment by thgreasi** [comment] 2018-02-03 16:17
Parsing short numeric only UUIDs for most actions should work on v6.12.8 .
I'm not sure whether we should keep this open, or close and open a new one to track support for numeric only complete UUIDs (eg `device register --uuid ...`).
See: https://github.com/resin-io/resin-cli/pull/774

**Comment by pimterry** [comment] 2018-02-05 10:12
@thgreasi I'm not sure about what your point about `device register` is, I thought this was all fixed for now. I'm going to leave this open until you're back to confirm, but I'm happy to close this in general if the practical issue is fixed, and we can resolve it in a more general sense in Capitano some time separately in future.

**Comment by thgreasi** [comment] 2018-02-05 14:06
@pimterry the fix was able to handle only short UUIDs. If you provide a 32 char long numeric only UUID Capitano will parse it as an integer which will be in the scientific form (eg 1234.56e28) which is above the MAX_SAFE_INTEGER. As a result precision issues corrupt the provided numeric UUID parameter in an unrecoverable manner. Hope that all these make sense.

**Comment by pimterry** [comment] 2018-02-05 14:55
Ah, gotcha. I think that's ok - doing some quick maths, I think you're 10x more likely to get struck by lightning this year than for any given 32 char UUID you generate to be all numbers. If we generate 10,000 a year, there's still a 99.7% chance that none of them are completely numeric. I think handling that case can wait until Capitano gets a big refresh. By the sounds of it, it'd definitely need work in Capitano anyway.

I'll close this for now, and we'll fix it more thoroughly in https://github.com/resin-io/capitano/issues/60

**Closed by pimterry** 2018-02-05 14:55 UTC
Labels: type:bug

**Comment by lekkas** [comment] 2018-02-06 13:10
Thank you for handling this @thgreasi
