### ISSUE TITLE
Registering the device should be optional

### ISSUE THREAD

**Issue by Tryum** [resin-io/resin-cli#349] opened 2016-06-03 13:17 UTC
I had issues flashing/configuring devices, and my resin.io account got filled with non-existing devices.

The resion.io should be done at the last moment, and should be optional.

**Comment by jviotti** [comment] 2016-06-06 13:39
Hi @Tryum ,

The problem is that we need to register a "device resource" in our backend in order to be able to proceed with configuration, so we can't delay that any further.

We do have logic to automatically remove the the created device resource if anything fails along the way. What error are you getting? You can get a stack trace and other helpful debug information by enabling the `DEBUG=true` environment variable (you can do `set DEBUG=true` in Windows).

**Comment by Tryum** [comment] 2016-06-06 13:40
Ok,

I think I aborted with ctrl+c, thus skipping the fail recovery ;)

Thibault Jochem
Software Engineer
EFREI Promo 2007

**Comment by jviotti** [comment] 2016-06-06 13:41
Ah I see. I believe we should be able to catch that signal. I'll make a note to investigate that further.

**Comment by Tryum** [comment] 2016-06-06 13:46
I think I aborted when I saw I could not select wifi over ethernet (other ticket).
And I may have done it twice to be sure it was broken ;)

**Comment by alexandrosm** [comment] 2016-06-06 18:12
@jviotti -- we should be creating the uuid locally and only provision in
resin after we have successfully written to the device -- is this possible?
The alternative approaches feel like workarounds more than solutions.

-- 

*Alexandros Marinos*

Founder & CEO, Resin.io


+1 206-637-5498

@alexandrosm

**Comment by jviotti** [comment] 2016-06-06 21:03
@alexandrosm I just took a closer look at this and thought about it for a while. I think I can envision a way to implement this without adding unnecessary complexity to the lower level commands that conform `quickstart`, so definitely worth a shot. I'll update this issue with my findings once I allocate some time to work on it.

**Comment by pimterry** [comment] 2018-02-06 12:57
I'm going to close this, as it's no longer relevant (nowadays devices typically register themselves on first boot), and is generally pretty out of date. Feel free to reopen or file a new issue if this is still a problem.

**Closed by pimterry** 2018-02-06 12:57 UTC
Labels: platform:all, type:feature
