### ISSUE TITLE
resin local should have ways to deploy container like resin deploy

### ISSUE THREAD

**Issue by imrehg** [resin-io/resin-cli#778] opened 2018-02-05 11:30 UTC
`resin local push` is very handy to locally work on a device, but all the containers are still built on the device itself. It would be useful to have a tool to do similar to `resin deploy`, where an already built container can be pushed onto the device (`resin local deploy`?)

[Forums](https://forums.resin.io/t/push-locally-built-docker-images-using-resin-local/2508)

**Comment by pimterry** [comment] 2018-02-06 12:00
True! But already filed - this is a duplicate of #613

**Closed by pimterry** 2018-02-06 12:00 UTC
