### ISSUE TITLE
User complains that CLI tools are too slow

### ISSUE THREAD

**Issue by alisondavis17** [resin-io/resin-cli#509] opened 2017-05-01 23:41 UTC
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1kjr)

**Comment by pimterry** [comment] 2017-11-14 19:12
This is going to get a lot quicker soon with prepackaging and bundling in #484.

I do agree it's important for us to speed the CLI up, but I'm going to close this ticket itself anyway, mostly just because I don't have any way to tell when it's 'done', and I'm trying to trim down the tickets to end up with a set of things we can prioritise, work on and tick off (like prepackaging itself).

Ideas for better ways to track ongoing open ended goals this are very welcome though - I think this makes a lot of sense for other tickets, but this is a kind of awkward case. Closing for now anyway.

**Closed by pimterry** 2017-11-14 19:12 UTC

**Comment by alisondavis17** [comment] 2017-11-14 20:09
@pimterry one thing I've been thinking about is creating product definition docs - not to track open ended goals, per se, but to define what a given product/component is designed to accomplish and what the ideal user experience should be. That could be a reference point that we constantly look to for guidance. 

For example, for the CLI, maybe part of the product definition would say "the experience should be fast and seamless." Then we could design features and fixes, such as prepackaging and bundling, to achieve that goal. 

These product definition docs could live with the components, as a reference point, similar to how architecture docs are meant to. They could also be living docs that change over time. 

Anyway, just a thought that your comment reminded me of.

**Comment by pimterry** [comment] 2017-11-15 14:18
@alisondavis17 that definitely sounds useful to me.

One thing that would be interesting is to have some clearer concrete definition of what descriptions like "the experience should be fast and seamless" mean - we could easily come up with some basic yes/no benchmarks (simple commands without network IO run in under 100ms, everything should run identically on all platforms using the platform-native CLI interface, etc). 

Knowing exactly what we're aiming for would give us useful metrics to look at incoming changes and decide whether potential performance penalties etc are problematic or acceptable, and to file bugs based on it if we find regressions (command X no longer runs nicely in Windows CMD) with a clear idea of what _should_ happen.

**Comment by alisondavis17** [comment] 2017-11-15 18:54
I like this idea of adding benchmarks as well.
