### ISSUE TITLE
Resin ssh command errors with rpc error: code = 2 desc = invalid character 'e' looking for beginning of value

### ISSUE THREAD

**Issue by c00w** [resin-io/resin-cli#686] opened 2017-10-11 08:03 UTC
- **resin-cli version:**
colin@rene ~/Downloads/resin-cli
 % resin version
6.6.10

- **Operating system and architecture:**
colin@rene ~/Downloads/resin-cli
 % lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

Error Output
colin@rene ~/gowork/src/github.com/c00w/overlord
 % resin ssh
? Select a device ... (...)
Connecting to: ...
rpc error: code = 2 desc = invalid character 'e' looking for beginning of value
Connection to ssh.resindevice.io closed.

**Comment by pimterry** [comment] 2017-10-11 11:08
Hi @c00w, thanks for the report, that's not good. There's some discussion of what looks like the same bug on our forums over here: https://forums.resin.io/t/terminal-giving-rpc-error-over-and-over-again/1491.

The error you're seeing there is coming from Docker on the device itself. What's happening is that you successfully ssh to the device, but when trying to enter the running application's container Docker implodes for some reason, and throws us out. I'd guess that this is a Docker bug, but we haven't confirmed that yet, and it could be some misconfiguration in ResinOS itself.

I am pretty confident it's not a CLI issue though: the CLI is very dumb in this regard, and the bit that's failing is definitely Docker on the OS itself. I'm going to close this issue because of that, but we should definitely look into this more - can you comment on the forum thread above, so our support team can take a look more closely? It'd be useful if you could include:

* the device type you're using
* the ResinOS version you're running
* whether this works for you from the web terminal
* whether this _always_ fails for you, or just occasionally

**Closed by pimterry** 2017-10-11 11:08 UTC
