### ISSUE TITLE
Cannot login with resin login

### ISSUE THREAD

**Issue by CameronDiver** [resin-io/resin-cli#552] opened 2017-06-14 08:12 UTC
If I select login via dashboard, two tabs are opened in a new browser window:
`www.https.com` and `file:////dashboard.resin.io/login/cli/http%25253A%25252F%25252Flocalhost%25253A8989%25252Fauth`. 
If I put `https://` instead of file on the second url, it still doesn't log me in, just takes me to the dashboard.

If I try to login with auth token, my terminal locks up. Ctrl+C, Ctrl+D and Enter all do nothing.

**Comment by pimterry** [comment] 2017-06-14 08:47
That's extremely weird, and I can't reproduce with my current local install. The auth token login sounds similar to what @emirotin has been hitting recently, which is a separate (but also very interesting) issue. Web login should be fine though. Can you let me know:

* What node version you're using
* What OS/browser you're using
* If you get any extra output when running with `DEBUG=1`
* If you've got `RESINRC_RESIN_URL` set in your environment
* If there's anything else you can think of that might cause weird behaviour for you here

The fact it doesn't work when changing the https is very weird too, and makes me more suspicious of your local env... Does the below link work for you?

https://dashboard.resin.io/login/cli/http%253A%252F%252Flocalhost%253A8989%252Fauth

For me, in Chrome when already logged into the dashboard, that reliably opens the dashboard CLI login page.

**Comment by pimterry** [comment] 2017-06-14 08:52
For context for anybody else hitting this: based on conversation [elsewhere](https://www.flowdock.com/app/rulemotion/resin-frontend/threads/lRyT41CsuuE0o7ZE4wWu3XRIQkW) it sounds like the 2nd issue (auth token login not working) is [this Node 8 bug](https://github.com/nodejs/node/issues/13557). Nothing we can do about that, but moving to Node < 8 should work ofc.

**Comment by emirotin** [comment] 2017-06-14 10:26
Hey @CameronDiver with node7 is the first thing still reproducible?

**Comment by CameronDiver** [comment] 2017-06-14 11:31
@emirotin No the first issue does not happen with node 7, logging in via the dashboard works fine.

**Comment by emirotin** [comment] 2017-06-14 11:45
OK I think it's safe to close then, probably related to the same node bug

**Closed by emirotin** 2017-06-14 11:45 UTC
