### ISSUE TITLE
SD card read error when running `resin device init`

### ISSUE THREAD

**Issue by mdtusz** [resin-io/resin-cli#662] opened 2017-09-19 20:00 UTC
- **resin-cli version: 6.6.6**
- **Operating system and architecture: OSX**

When running `resin device init`, the following error is thrown:

```
myDir|master⚡ ⇒ resin device init
? Select an application myApplication (raspberrypi3)
Getting device operating system for raspberrypi3
The image was downloaded successfully
Registering to myApplication: 0ae449beef92da12caece6764639ed1830b7e2a8bafb1e1fda1944600d57a6
Configuring operating system image
? Network Connection wifi
? Wifi SSID mySSID
? Wifi Passphrase **********************
{ Error: Invalid volume signature!
    at Object.exports.init (/usr/local/lib/node_modules/resin-cli/node_modules/fatfs/vol.js:7:69)
    at init (/usr/local/lib/node_modules/resin-cli/node_modules/fatfs/index.js:64:35)
    at /usr/local/lib/node_modules/resin-cli/node_modules/fatfs/index.js:49:21
    at /usr/local/lib/node_modules/resin-cli/node_modules/resin-image-fs/build/driver.js:52:16
    at FSReqWrap.wrapper [as oncomplete] (fs.js:665:17)
  cause:
   Error: Invalid volume signature!
       at Object.exports.init (/usr/local/lib/node_modules/resin-cli/node_modules/fatfs/vol.js:7:69)
       at init (/usr/local/lib/node_modules/resin-cli/node_modules/fatfs/index.js:64:35)
       at /usr/local/lib/node_modules/resin-cli/node_modules/fatfs/index.js:49:21
       at /usr/local/lib/node_modules/resin-cli/node_modules/resin-image-fs/build/driver.js:52:16
       at FSReqWrap.wrapper [as oncomplete] (fs.js:665:17),
  isOperational: true }
```

This occurs while using a 16gb (micro) sd card, both when mounted and unmounted, and both when the device (`/dev/disk2`) is included or omitted from the command.

**Comment by pimterry** [comment] 2017-09-22 10:22
Ah, I see, thanks for the report. We've been holding on dev recently as part of redesigning the CLI, and we've some outstanding bugs at the moment in image configuration for ResinOS v2 images, which I suspect is causing this.

I don't have a CLI workaround I can guarantee right now. You may be able to make this work with `resin os download`, `resin local configure` including setting the hostname, and then `resin os initialize`, but I'm not sure. 

The reliable workaround for now is to download a configured image through the dashboard instead, and then run `resin os initialize` to flash it to your disk, or use [Etcher](https://etcher.io). My top priority for the next few weeks is these major CLI bug fixes though, before we move onto an big CLI update, so we should have a proper solution for you soon!

**Comment by pimterry** [comment] 2017-11-29 12:30
@mdtusz We've sorted out a long list of other outstanding issues with the CLI around this image configuration work now, and I currently can't reproduce this. Can you? I suspect it's now been fixed incidentally as part of the other fixes. If you can reproduce it, let me know exactly which image you're using and I'll take a closer look.

**Comment by pimterry** [comment] 2017-12-11 14:09
I'm going to close this as fixed for now - feel free to reopen with details if you can reproduce this.

**Closed by pimterry** 2017-12-11 14:09 UTC
Labels: priority:high, type:bug
