### ISSUE TITLE
ignore config partition which now auto-mounts

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/resin-cli#98] opened 2015-07-20 11:47 UTC

**Comment by shaunmulligan** [comment] 2015-07-20 11:49
The new device images now have an automounting config partition. This partition shows up in the drives list when you run quickstart.

**Comment by jviotti** [comment] 2015-08-14 17:36
Resin CLI Visuals (https://github.com/resin-io/resin-cli-visuals) contains the drive widget. Should be easy to filter it out before showing the options to the user.

**Comment by jviotti** [comment] 2015-08-14 19:40
I'm unable to reproduce this issue. I've burned a Raspberry Pi 2 image downloaded from production (I can see both the boot and config partitions mounted on my desktop), however I still not see the config partition showing up in the drive list:

<img width="507" alt="screenshot 2015-08-14 15 39 11" src="https://cloud.githubusercontent.com/assets/2192773/9282466/a1d1413c-429a-11e5-93ef-fdbb931d82a6.png">

**Comment by jviotti** [comment] 2015-08-18 15:19
Closing since I cannot reproduce (tried in various ways). Please re-open with more information about how to reproduce reliably in case it happens again.

**Closed by jviotti** 2015-08-18 15:19 UTC
Labels: bug, can't reproduce
