### ISSUE TITLE
resin device [device name] does't seem to work

### ISSUE THREAD

**Issue by lorenzo-stoakes** [resin-io/resin-cli#19] opened 2015-04-16 17:04 UTC
I tried the below, which doesn't seem correct:-

```bash
[~]$ resin devices --app foobar                                                                                                                                                                                     
ID    NAME DEVICE TYPE  IS ONLINE APPLICATION NAME STATUS LAST SEEN
12022 one  raspberry-pi false     foobar           Idle            
[~]$ resin device one                                                                                                                                                                                               
Device not found: one
```

**Comment by jviotti** [comment] 2015-04-27 13:36
Weird, I can't reproduce here:

```sh
1 fix/logs-messages Projects/resin/resin-cli/
$ ./bin/resin apps
ID   APP NAME      DEVICE TYPE      ONLINE DEVICES DEVICES LENGTH
1750 Hello123      raspberry-pi     0              0
1409 HelloSDK      raspberry-pi     0              0
1443 HelloWorld    raspberry-pi     0              0
1751 HelloWorld123 raspberry-pi     0              0
1299 MuSync        raspberry-pi     0              0
1748 MyHelloApp    raspberry-pi     0              0
1749 MyHelloApp2   raspberry-pi     0              0
1747 MyNewApp      raspberry-pi     0              0
2148 ResinWatch    raspberry-pi     0              1
1984 Rpi2          raspberry-pi2    0              0
1482 RPIRaw        raspberry-pi     0              0
1189 Sonus         raspberry-pi     0              0
2068 TestBBB       beaglebone-black 0              0

0 fix/logs-messages Projects/resin/resin-cli/
$ ./bin/resin devices -a ResinWatch
ID    NAME DEVICE TYPE  IS ONLINE APPLICATION NAME STATUS LAST SEEN
13010 Pi1  raspberry-pi false     ResinWatch       Idle

0 fix/logs-messages Projects/resin/resin-cli/
$ ./bin/resin device Pi1
ID: 13010
NAME: Pi1
DEVICE TYPE: raspberry-pi
IS ONLINE: false
IP ADDRESS: 10.2.1.114 192.168.2.7
APPLICATION NAME: ResinWatch
STATUS: Idle
LAST SEEN: undefined
UUID: be283dcbc7a5c7810ae534f434d820933ef74a688a4996544f5a67b1c749c3
COMMIT: a81ee12bbd816f382f796c6b8b3c3f385f7e1f92
SUPERVISOR VERSION: 0.0.12
IS WEB ACCESSIBLE: false
NOTE: null
```

**Comment by jviotti** [comment] 2015-04-29 13:19
Closing as it seems to got fixed with another patch. I'll reopen if it happens again.

**Closed by jviotti** 2015-04-29 13:19 UTC
Labels: bug
