### ISSUE TITLE
ENV is ignored if using --emulated

### ISSUE THREAD

**Issue by fermuch** [resin-io/resin-cli#747] opened 2018-01-01 13:42 UTC
- **resin-cli version:** 6.12.0
- **Operating system and architecture:** arch linux x64

### Demo Dockerfile
```dockerfile
FROM resin/raspberry-pi-node:9-slim
ENV foo=bar
RUN printenv
```

If it's run without `--emulated`, it sets env correctly:
```bash
$ resin build --tag foo-bar --application barfoo --deviceType raspberrypi3 --arch armhf .
[Info]    Building Standard Dockerfile project
[Build]   Step 1/20 : FROM resin/raspberry-pi-node:9-slim
[Build]    ---> 92e612e3621f
[Build]   Step 2/20 : ENV foo bar
[Build]    ---> Running in 4aecb0c9cd84
[Build]    ---> bb46f11cabd1
```

With `--emulated`:
```bash
$ resin build --emulated --tag foo-bar --application barfoo --deviceType raspberrypi3 --arch armhf .
[Info]    Running emulated build
[Info]    Building Standard Dockerfile project
[Build]   Step 1/21 : FROM resin/raspberry-pi-node:9-slim
[Build]    ---> 92e612e3621f
[Build]   Step 2/21 : ENV [object Object]
[Build]    ---> c5d7f5d20688
```

**NOTE:** If I run `printenv` inside the container, I can see an env variable `[object Object]`, so I can confirm it's not only a visual bug.
**NOTE:** Build args are ignored if it's built with `--emulated`, same as with `ENV`.

---------------------

Weird things that might be affecting my setup:
- I'm using docker over the lan (with env variables, $DOCKER_HOST and so on)

Some things that might help debug:
- The remote docker version is: `Docker version 17.09.0-ce, build afdb6d4`
- I'm using fish shell as the user's shell. I tried running the build with bash, but since my user has that shell as the default one and I don't know if resin is spawning a new shell, it could be related.

--------------------

Have a great 2018! Hope we can hack together this year :smile:

**Comment by pimterry** [comment] 2018-01-02 11:02
Great report, thanks! I'll take a proper look shortly, but at first read that looks like a pretty clear cut bug to me, shouldn't be too hard to track down.

**Comment by pimterry** [comment] 2018-01-02 18:19
@fermuch I've got a fix for this for the `ENV` case ready, in the PR linked just above.

> Build args are ignored if it's built with --emulated, same as with ENV.

I can't seem to reproduce this, in my very basic testing: it looks like the emulated Dockerfile we produce for `ARG` is exactly what I'd expect. Can you be more specific? An example Dockerfile & CLI command like the above that works until you enable emulation would be really helpful to pin this down.

**Comment by fermuch** [comment] 2018-01-02 20:31
Whoops! The build args bug was a mistake on my side. I was using the build arg before declaring `ARG`. I've moved all the ARGs to the header of the Dockerfile and they are working okay.

Thanks for such a fast answer & fix! Is there some way I can help you by testing the PR with my project, or should I just wait until it lands on a new version?

**Comment by pimterry** [comment] 2018-01-04 12:46
> Whoops! The build args bug was a mistake on my side. I was using the build arg before declaring ARG. I've moved all the ARGs to the header of the Dockerfile and they are working okay.

Good to hear! I've updated the issue title.

> Thanks for such a fast answer & fix! Is there some way I can help you by testing the PR with my project, or should I just wait until it lands on a new version?

Happily, it's now landed. The patch for the submodule has been released, which should be automatically picked up by all new CLI installs. A quick `npm uninstall -g resin-cli && npm install -g resin-cli` should get everything working again. I'm going to close this as resolved, but do ping here if you're still seeing issues with this.

Thanks for the report!

**Closed by pimterry** 2018-01-04 12:46 UTC
Labels: priority:high, type:bug
