### ISSUE TITLE
Undefined downloads

### ISSUE THREAD

**Issue by Davidnet** [resin-io/resin-cli#799] opened 2018-02-27 22:28 UTC
I haven't been able to install resin-cli in debian jessie, I'm encountering the following errors: 
```
node-pre-gyp ERR! Tried to download(undefined): https://github.com/resin-io/node-ext2fs/releases/download/v0.1.1/bindings-v0.1.1-node-v59-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for ext2fs@0.1.1 and node@9.6.1 (node-v59 ABI, glibc) (falling back to source compile with node-gyp)
```
- **resin-cli version:** (N/A) trying to install last version with --global and --production
- **Operating system and architecture:** debian jessie and x86_64

**Comment by pimterry** [comment] 2018-02-28 10:50
The URL in there does download successfully for me. Perhaps this was just a temporary github blip - can you reproduce this now @Davidnet? You can see the built node-ext2fs binaries at https://github.com/resin-io/node-ext2fs/releases/tag/v0.1.1, this one should definitely exist.

**Comment by pimterry** [comment] 2018-03-13 18:28
@Davidnet I believe this was actually caused by #805 - `--unsafe-perm` is now required as an option to `npm install` on some systems. That's now in the documentation, which should make it easier to avoid in future.

Assuming that's true, I'm going to close this ticket, but do let us know if you're still seeing issues installing with that option.

**Closed by pimterry** 2018-03-13 18:28 UTC
