### ISSUE TITLE
UNABLE TO GET ISSURE CERT LOCALLY

### ISSUE THREAD

**Issue by 200018171** [resin-io/resin-cli#347] opened 2016-06-02 21:35 UTC
Using resin client behind a company firewall and I get the following error using resin-cli:

> UNABLE TO GET ISSURE CERT LOCALLY: unable to get local issuer certificate

I have tried to set strict ssl to false as a work around, but that doesn't work. 

> npm config set strict-ssl=false

I'm working off an ubuntu 14.04 system and I've had to add internal certificates to get most https links to work, so I suspect the requested certificate is in my bundled certs at /etc/ssl/certs/ca-certificates.crt

Can someone help me to debug this issue? I need to know what cert it's failing and also if I need to configure resin-cli with reference to my system's certificates bundle.

Thanks!
-Adam McCann
GE Global Research

**Comment by 200018171** [comment] 2016-06-06 14:20
I get the same issue with any command:

>$ resin help
UNABLE_TO_GET_ISSUER_CERT_LOCALLY: unable to get local issuer certificate

**Comment by jviotti** [comment] 2016-06-06 14:34
Hi @200018171 ,

I see. I found some NPM related workarounds like the one you said you tried before, however I don't think that's the way to go give that the error is been caused by the CLI, and not by NPM.

What I'd do is the following:

- Try to find where the CLI NPM package was installed in your system. In the source code directory, edit `node_modules/resin-request/build/request.js` and change `strictSSL: true` to `strictSSL: false` in https://github.com/resin-io-modules/resin-request/blob/master/build/request.js#L50.

Also, what NodeJS version are you running?

**Comment by pimterry** [comment] 2017-05-05 09:36
Closing, feel free to reopen with more details if this is still an issue.

**Closed by pimterry** 2017-05-05 09:36 UTC
Labels: platform:linux, type:bug
