### ISSUE TITLE
Updating Resin CLI failed

### ISSUE THREAD

**Issue by svenschwermer** [resin-io/resin-cli#888] opened 2018-06-04 11:48 UTC
- **resin-cli version:** latest (7.5.1)
- **Operating system and architecture:** Mac OSX amd64

I just ran `npm install resin-cli -g --production --unsafe-perm` to update my existing installation. This is the error I'm getting:

```
[...]
  LIBTOOL-STATIC Release/libext2fs.a
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 246, in ExecFilterLibtool
    if not libtool_re.match(line) and not libtool_re5.match(line):
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/libext2fs.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/resin-cli/node_modules/ext2fs
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ext2fs@1.0.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ext2fs@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_c5rf)

**Comment by pimterry** [comment] 2018-06-12 15:17
Hi @svenschwermer, sorry we didn't catch this here, I see this has been resolved with support, so I'm going to close this ticket for now.

In general if you hit more issues in future, contacting support is the right thing to do. CLI github issues are primarily used for CLI planning and development, rather than as a support channel. We do catch up with issues here at reasonable intervals, but they aren't formally monitored & managed in the way our official support channels are. Sorry if that's caused you any trouble!

Some extra background here for posterity: this build issue is caused by Python 3, which isn't supported by node-gyp, and this was resolved by using 2.7 instead. That's being documented long-term in https://github.com/resin-io/resin-cli/pull/893, so I'll close this issue for now.

**Closed by pimterry** 2018-06-12 15:17 UTC
