### ISSUE TITLE
`resin sync` results in `ResinRequestError: Request error: App not found`

### ISSUE THREAD

**Issue by thisisbrians** [resin-io/resin-cli#937] opened 2018-08-02 16:01 UTC
- **resin-cli version:** 7.6.2
- **Operating system and architecture:** MacOS Hish Sierra 10.13.6 MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports) 3.5 GHz Intel Core i7
- Node v10.0.0
- NPM 6.2.0

`.resin-sync.yml`:

```local_resinos:
  app-name: vaporware
  build-triggers:
    - Dockerfile: 4e79c33215723b0cb5e641f00cedfcaf620073d5048f25d8fc1cc9c617c7637d
  environment:
    - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    - BRACTLET_BAS_TRENDING_ENABLE=0
    - BRACTLET_DHCP_ENABLE=1
    - BRACTLET_POWER_METER_TRENDING_ENABLE=1
    - BRACTLET_STATIC_IP_ADDRESS=192.168.1.235
    - BRACTLET_STATIC_NETMASK=255.255.255.0
    - BRACTLET_STATIC_GATEWAY=192.168.1.1
    - BRACTLET_WIRED_INTERNET_ENABLE=1
    - BRACTLET_WIRED_INTERFACE_ENABLE=1
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
uuid: 6876cb1
```

Full error message after running `resin sync`:

```Getting information for device: 6876cb1
Got application container info.
resin sync failed. ResinRequestError: Request error: App not found
ResinRequestError: Request error: App not found

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/resin-io/resin-cli/issues/new
  Forums: https://forums.resin.io
```

**Comment by pimterry** [comment] 2018-08-07 15:54
This was caused by the device being in local mode, and was handled via support. In summary: resin sync is designed for syncing to a live production (non-local mode) device, and local push should be used instead if you're looking for local development tools.

I'll close this issue for now, since there's nothing else outstanding here.

**Closed by pimterry** 2018-08-07 15:54 UTC
