### ISSUE TITLE
Cannot install resin-cli on Alpine linux (docker base image)

### ISSUE THREAD

**Issue by jcozar87** [resin-io/resin-cli#894] opened 2018-06-13 06:51 UTC
- **resin-cli version: 7.5.2**
- **Operating system and architecture: mac os x (docker: Alpine linux), i386**

When I try to install the resin-cli latest version on docker base image, which is an Alpine Linux distribution, it fails:

```
../deps/e2fsprogs/lib/ext2fs/getsectsize.c:34:22: fatal error: linux/fd.h: No such file or directory
 #include <linux/fd.h>
                      ^
compilation terminated.
make: *** [ext2fs.target.mk:179: Release/obj.target/ext2fs/deps/e2fsprogs/lib/ext2fs/getsectsize.o] Error 1
make: Leaving directory '/usr/lib/node_modules/resin-cli/node_modules/ext2fs/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.9.87-linuxkit-aufs
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/resin-cli/node_modules/ext2fs
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: removedrive@1.1.2 (node_modules/resin-cli/node_modules/removedrive):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for removedrive@1.1.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: macmount@1.0.0 (node_modules/resin-cli/node_modules/macmount):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for macmount@1.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ext2fs@1.0.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ext2fs@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-13T06_39_20_427Z-debug.log
```

Probably, the problem is related with _musl_ and _glibc_. I read that _glibc_ is the standard default library in most of the linux distributions, but in Alpine _musl_ is used. I attach the Dockerfile that I am using:

```
FROM docker

RUN apk --update --no-cache add bash git python python3 make openssh g++ nodejs nodejs-npm yarn
RUN npm install resin-cli -g --production --unsafe-perm
```

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_c6mr)

**Comment by pimterry** [comment] 2018-06-13 11:00
Hi @jcozar87. Can you post more of the install log here? What should happen is that npm installs use prebuild releases of ext2fs, which avoid the need to manage the build environment. The built binaries are hosted here: https://github.com/resin-io/node-ext2fs/releases/. There'll probably be an error somewhere in the logs where it tries to look up some specific configuration from there which doesn't exist.

In addition, as an alternative, we also have a prebuilt standalone build which avoids the need to use node & npm directly entirely. See ['standalone install' in the readme](https://github.com/resin-io/resin-cli#standalone-install). Does that work for you? It's not quite as stable yet, but long term we're planning on moving in that direction and moving away from npm installs entirely, to avoid exactly these kind of problems.

**Comment by pimterry** [comment] 2018-06-25 18:06
@jcozar87 I think that means something went wrong in the unzipping process, and the binary has the wrong permissions. If you run `chmod +x ./resin-cli/resin`, you should be able to run it as `resin` directly. Does that work for you?

The zip itself includes the permissions metadata that should do that for you, so I suspect this means you've done something unusual in unzipping the build. In future we'll have a proper installer, so you won't even need to think about that.

**Comment by pimterry** [comment] 2018-06-26 16:35
I'm going to close this - the original issue here was actually caused by a partially failed publish of ext2fs (https://github.com/resin-io/node-ext2fs/issues/30), which is why you had to do a native install in the first place.

You should be able to reinstall from scratch with npm and have everything work now, or you can continue using the standalone build as above instead if it's working nicely for you. Thanks for reporting this!

**Closed by pimterry** 2018-06-26 16:35 UTC
