### ISSUE TITLE
6.1.0 failing to install in current docker:dind

### ISSUE THREAD

**Issue by BrianAdams** [resin-io/resin-cli#591] opened 2017-07-12 01:46 UTC
Works with 5.11.1 but not the most recent version

Not sure what is wrong here.  The steps I am using:
```
docker run -it --rm docker:dind /bin/sh
apk add nodejs nodejs-npm python python-dev git ruby expect py-pip build-base --update-cache
npm install --global --production resin-cli
```

```
 # npm install --global --production resin-cli
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
/usr/bin/resin -> /usr/lib/node_modules/resin-cli/bin/resin

> drivelist@5.0.25 install /usr/lib/node_modules/resin-cli/node_modules/drivelist
> node-gyp rebuild

gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/6.10.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/resin-cli/node_modules/drivelist/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: getaddrinfo EAI_AGAIN nodejs.org:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1018:11)
gyp ERR! stack     at errnoException (dns.js:33:15)
gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
gyp ERR! System Linux 4.9.31-moby
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/resin-cli/node_modules/drivelist
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
/usr/lib
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: removedrive@^1.0.0 (node_modules/resin-cli/node_modules/removedrive):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for removedrive@1.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: macmount@^1.0.0 (node_modules/resin-cli/node_modules/denymount/node_modules/macmount):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for macmount@1.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 4.9.31-moby
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--global" "--production" "resin-cli"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! drivelist@5.0.25 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the drivelist@5.0.25 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the drivelist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs drivelist
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls drivelist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
npm ERR! code 1
```

**Comment by pimterry** [comment] 2017-07-12 10:40
I've just tested locally, and those exact commands in that same container work nicely for me, so I don't think there's a resin-cli issue here.

It looks like the specific failure in that message is a `getaddrinfo` error for nodejs.org - it's a failing DNS lookup. I suspect that's a general issue on your network, or just an intermittent error that'll disappear if you try again. Can you still reproduce this issue?

**Comment by pimterry** [comment] 2017-08-16 15:47
I'm going to close this for now - feel free to reopen if you're still seeing this.

**Closed by pimterry** 2017-08-16 15:47 UTC
